/**
 * Validate tango-node SDK against the canonical API filter/shape manifest.
 *
 * Port of `scripts/check_filter_shape_conformance.py` from tango-python.
 *
 * Reads the manifest (generated by tango) and checks that the SDK exposes the
 * appropriate filter params on every list_/get_ method, and that every
 * `ShapeConfig` default parses + validates against an explicit schema.
 *
 * Uses the TypeScript Compiler API to introspect `src/client.ts` — interfaces
 * are types, not values, so a pure runtime probe wouldn't catch type-only
 * filter declarations.
 *
 * Usage:
 *   npx tsx scripts/check-filter-shape-conformance.ts \
 *     --manifest ../tango/contracts/filter_shape_contract.json
 *
 * Or programmatically:
 *   import { runConformance } from "./check-filter-shape-conformance.ts";
 *   const { errors, warnings } = await runConformance({ manifestPath, clientPath, configPath });
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as ts from "typescript";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const DEFAULT_CLIENT_PATH = path.join(REPO_ROOT, "src", "client.ts");
const DEFAULT_CONFIG_PATH = path.join(REPO_ROOT, "src", "config.ts");
const DEFAULT_MANIFEST_PATH = path.resolve(
  REPO_ROOT,
  "..",
  "tango",
  "contracts",
  "filter_shape_contract.json",
);

// ---------------------------------------------------------------------------
// Resource → SDK method mapping
// ---------------------------------------------------------------------------
// Decided by the SDK, not by the API. `null` = intentionally not implemented.

export const RESOURCE_TO_METHOD: Record<string, string | null> = {
  contracts: "listContracts",
  idvs: "listIdvs",
  vehicles: "listVehicles",
  otas: "listOtas",
  otidvs: "listOtidvs",
  subawards: "listSubawards",
  organizations: "listOrganizations",
  opportunities: "listOpportunities",
  notices: "listNotices",
  forecasts: "listForecasts",
  grants: "listGrants",
  entities: "listEntities",
  agencies: "listAgencies",
  naics: "listNaics",
  gsa_elibrary_contracts: "listGsaElibraryContracts",
  itdashboard: "listItDashboard",
  budget_accounts: "listBudgetAccounts",
  offices: "listOffices",
};

// ---------------------------------------------------------------------------
// ShapeConfig entries (name → model name in the explicit schema registry)
// ---------------------------------------------------------------------------

interface ShapeEntry {
  shapeName: string;
  modelName: string;
}

const SHAPE_CONFIG_ENTRIES: ShapeEntry[] = [
  { shapeName: "CONTRACTS_MINIMAL", modelName: "Contract" },
  { shapeName: "ENTITIES_MINIMAL", modelName: "Entity" },
  { shapeName: "ENTITIES_COMPREHENSIVE", modelName: "Entity" },
  { shapeName: "FORECASTS_MINIMAL", modelName: "Forecast" },
  { shapeName: "OPPORTUNITIES_MINIMAL", modelName: "Opportunity" },
  { shapeName: "NOTICES_MINIMAL", modelName: "Notice" },
  { shapeName: "GRANTS_MINIMAL", modelName: "Grant" },
  { shapeName: "IDVS_MINIMAL", modelName: "IDV" },
  { shapeName: "IDVS_COMPREHENSIVE", modelName: "IDV" },
  { shapeName: "VEHICLES_MINIMAL", modelName: "Vehicle" },
  { shapeName: "VEHICLES_COMPREHENSIVE", modelName: "Vehicle" },
  { shapeName: "VEHICLE_AWARDEES_MINIMAL", modelName: "IDV" },
  // The following ShapeConfig entries do not yet have a registered explicit
  // schema in src/shapes/explicitSchemas.ts. They will be reported as warnings.
  { shapeName: "ORGANIZATIONS_MINIMAL", modelName: "Organization" },
  { shapeName: "OTAS_MINIMAL", modelName: "OTA" },
  { shapeName: "OTIDVS_MINIMAL", modelName: "OTIDV" },
  { shapeName: "SUBAWARDS_MINIMAL", modelName: "Subaward" },
  { shapeName: "GSA_ELIBRARY_CONTRACTS_MINIMAL", modelName: "GsaElibraryContract" },
  { shapeName: "ITDASHBOARD_INVESTMENTS_MINIMAL", modelName: "ITDashboardInvestment" },
  { shapeName: "ITDASHBOARD_INVESTMENTS_COMPREHENSIVE", modelName: "ITDashboardInvestment" },
  { shapeName: "VEHICLE_ORDERS_MINIMAL", modelName: "Contract" },
  { shapeName: "PROTESTS_MINIMAL", modelName: "Protest" },
];

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

interface ResourceManifest {
  runtime?: {
    filter_params?: string[];
    ordering_fields?: string[];
    pagination?: { class?: string };
  };
}

interface Manifest {
  resources?: Record<string, ResourceManifest>;
}

// ---------------------------------------------------------------------------
// AST helpers
// ---------------------------------------------------------------------------

interface MethodInfo {
  name: string;
  optionsTypeName: string | null;
}

interface InterfaceInfo {
  name: string;
  members: Set<string>;
  hasIndexSignature: boolean;
  extends: string[];
}

interface ClientAst {
  methods: Map<string, MethodInfo>;
  interfaces: Map<string, InterfaceInfo>;
}

/**
 * Parse `src/client.ts` and extract method signatures + interface members.
 */
export function parseClientAst(clientPath: string): ClientAst {
  const source = fs.readFileSync(clientPath, "utf8");
  const sourceFile = ts.createSourceFile(
    clientPath,
    source,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true,
    ts.ScriptKind.TS,
  );

  const methods = new Map<string, MethodInfo>();
  const interfaces = new Map<string, InterfaceInfo>();

  // Walk top-level statements
  for (const stmt of sourceFile.statements) {
    if (ts.isInterfaceDeclaration(stmt)) {
      interfaces.set(stmt.name.text, extractInterfaceInfo(stmt));
    } else if (ts.isClassDeclaration(stmt)) {
      // Collect method declarations on the class (e.g. TangoClient)
      for (const member of stmt.members) {
        if (!ts.isMethodDeclaration(member)) continue;
        if (!member.name || !ts.isIdentifier(member.name)) continue;
        const methodName = member.name.text;
        if (!isListOrGet(methodName)) continue;

        // Find the `options` parameter (or the second parameter when the
        // first is a positional id like `key` / `uei` / `code`).
        const optionsTypeName = extractOptionsTypeName(member);
        methods.set(methodName, { name: methodName, optionsTypeName });
      }
    }
  }

  return { methods, interfaces };
}

function isListOrGet(name: string): boolean {
  return /^(list|get)[A-Z]/.test(name);
}

function extractInterfaceInfo(decl: ts.InterfaceDeclaration): InterfaceInfo {
  const members = new Set<string>();
  let hasIndexSignature = false;
  for (const member of decl.members) {
    if (ts.isPropertySignature(member) && member.name && ts.isIdentifier(member.name)) {
      members.add(member.name.text);
    } else if (
      ts.isPropertySignature(member) &&
      member.name &&
      ts.isStringLiteral(member.name)
    ) {
      members.add(member.name.text);
    } else if (ts.isIndexSignatureDeclaration(member)) {
      hasIndexSignature = true;
    }
  }

  const extendsList: string[] = [];
  if (decl.heritageClauses) {
    for (const clause of decl.heritageClauses) {
      if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
      for (const t of clause.types) {
        if (ts.isIdentifier(t.expression)) {
          extendsList.push(t.expression.text);
        }
      }
    }
  }

  return { name: decl.name.text, members, hasIndexSignature, extends: extendsList };
}

/**
 * Find the type name of the `options` parameter for a method.
 * Handles two cases:
 *   - `async listFoo(options: ListFooOptions = {}): ...`
 *   - `async listEntityContracts(uei: string, options: EntitySubresourceOptions = {}): ...`
 * Returns null if the method doesn't take an Options-typed argument we can
 * statically resolve (e.g. inline object types, no params, generics).
 */
function extractOptionsTypeName(method: ts.MethodDeclaration): string | null {
  for (const param of method.parameters) {
    if (!param.name || !ts.isIdentifier(param.name)) continue;
    // Accept `options` and `_options` (unused-param convention).
    if (param.name.text !== "options" && param.name.text !== "_options") continue;
    const typeNode = param.type;
    if (!typeNode) return null;
    // Direct type reference: `options: ListContractsOptions`
    if (ts.isTypeReferenceNode(typeNode) && ts.isIdentifier(typeNode.typeName)) {
      return typeNode.typeName.text;
    }
    // Intersection: `options: ListContractsOptions & { cursor?: ... }`
    if (ts.isIntersectionTypeNode(typeNode)) {
      for (const t of typeNode.types) {
        if (ts.isTypeReferenceNode(t) && ts.isIdentifier(t.typeName)) {
          return t.typeName.text;
        }
      }
    }
    return null;
  }
  return null;
}

/**
 * Recursively collect all member names + index-signature flag for an
 * interface, walking `extends` chains.
 */
export function resolveInterface(
  name: string,
  interfaces: Map<string, InterfaceInfo>,
  seen: Set<string> = new Set(),
): { members: Set<string>; hasIndexSignature: boolean; found: boolean } {
  if (seen.has(name)) {
    return { members: new Set(), hasIndexSignature: false, found: true };
  }
  seen.add(name);

  const info = interfaces.get(name);
  if (!info) {
    return { members: new Set(), hasIndexSignature: false, found: false };
  }

  const members = new Set<string>(info.members);
  let hasIndexSignature = info.hasIndexSignature;

  for (const parent of info.extends) {
    const parentInfo = resolveInterface(parent, interfaces, seen);
    for (const m of parentInfo.members) members.add(m);
    if (parentInfo.hasIndexSignature) hasIndexSignature = true;
  }

  return { members, hasIndexSignature, found: true };
}

// ---------------------------------------------------------------------------
// Filter conformance
// ---------------------------------------------------------------------------

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

/**
 * Names the SDK could plausibly expose for a manifest filter param:
 * raw snake_case form + camelCase form.
 */
function candidateNames(filterParam: string): string[] {
  const camel = snakeToCamel(filterParam);
  return camel === filterParam ? [filterParam] : [filterParam, camel];
}

export interface ConformanceResult {
  manifest: string;
  errors: string[];
  warnings: string[];
}

export interface RunConformanceOptions {
  manifestPath: string;
  clientPath?: string;
  configPath?: string;
  /** When true, skip the ShapeConfig validation pass. */
  skipShapes?: boolean;
  /** Override resource → method mapping (used by tests). */
  resourceMap?: Record<string, string | null>;
}

/**
 * Run the full conformance check against the given manifest.
 */
export function runConformance(opts: RunConformanceOptions): ConformanceResult {
  const manifestPath = path.resolve(opts.manifestPath);
  const clientPath = opts.clientPath ?? DEFAULT_CLIENT_PATH;
  const configPath = opts.configPath ?? DEFAULT_CONFIG_PATH;
  const resourceMap = opts.resourceMap ?? RESOURCE_TO_METHOD;

  const errors: string[] = [];
  const warnings: string[] = [];

  if (!fs.existsSync(manifestPath)) {
    errors.push(`manifest not found: ${manifestPath}`);
    return { manifest: manifestPath, errors, warnings };
  }
  if (!fs.existsSync(clientPath)) {
    errors.push(`client source not found: ${clientPath}`);
    return { manifest: manifestPath, errors, warnings };
  }

  const manifest: Manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const ast = parseClientAst(clientPath);

  const resources = manifest.resources ?? {};

  for (const [resourceName, payload] of Object.entries(resources)) {
    const sdkMethod = resourceMap[resourceName];
    const runtimeFilters = payload?.runtime?.filter_params ?? [];

    if (sdkMethod === null) {
      if (runtimeFilters.length > 0) {
        warnings.push(`${resourceName}: no SDK method implemented for this resource`);
      }
      continue;
    }

    if (sdkMethod === undefined) {
      // Resource appears in the manifest but is not in our explicit map.
      if (runtimeFilters.length > 0) {
        warnings.push(
          `${resourceName}: no SDK method mapped in conformance script (add to RESOURCE_TO_METHOD)`,
        );
      }
      continue;
    }

    const methodInfo = ast.methods.get(sdkMethod);
    if (!methodInfo) {
      errors.push(`${resourceName}: mapped method \`${sdkMethod}\` not found in SDK client`);
      continue;
    }

    if (!methodInfo.optionsTypeName) {
      if (runtimeFilters.length > 0) {
        warnings.push(
          `${resourceName}: \`${sdkMethod}\` has no resolvable Options interface — cannot statically check filters`,
        );
      }
      continue;
    }

    const resolved = resolveInterface(methodInfo.optionsTypeName, ast.interfaces);
    if (!resolved.found) {
      errors.push(
        `${resourceName}: Options interface \`${methodInfo.optionsTypeName}\` for \`${sdkMethod}\` not found`,
      );
      continue;
    }

    const exposed = resolved.members;
    const missing: string[] = [];
    for (const filter of runtimeFilters) {
      const candidates = candidateNames(filter);
      const isExposed = candidates.some((c) => exposed.has(c));
      if (!isExposed) missing.push(filter);
    }

    if (missing.length === 0) continue;

    if (resolved.hasIndexSignature) {
      // SDK relies on its `[key: string]: unknown` escape hatch for these.
      // Mirrors Python's `**kwargs` warning.
      warnings.push(
        `${resourceName}: \`${sdkMethod}\` relies on index signature for filters: ${missing.join(", ")}`,
      );
    } else {
      errors.push(
        `${resourceName}: \`${sdkMethod}\` missing runtime filters: ${missing.join(", ")}`,
      );
    }
  }

  // -----------------------------------------------------------------------
  // Shape conformance
  // -----------------------------------------------------------------------
  if (!opts.skipShapes) {
    const shapeResult = runShapeCheck(configPath);
    errors.push(...shapeResult.errors);
    warnings.push(...shapeResult.warnings);
  }

  return { manifest: manifestPath, errors, warnings };
}

// ---------------------------------------------------------------------------
// Shape conformance
// ---------------------------------------------------------------------------

interface ShapeCheckResult {
  errors: string[];
  warnings: string[];
}

/**
 * For every ShapeConfig constant, parse the shape string and validate that
 * each referenced field exists in the explicit schema for that model.
 *
 * This pulls in the SDK's own parser + schema registry — same behavior as
 * the Python equivalent.
 */
function runShapeCheck(configPath: string): ShapeCheckResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Lazy-import the SDK so the script doesn't crash when the consumer hasn't
  // built `dist/` yet. We import from the source via the same `.js` aliases
  // used in the codebase — works under tsx / vitest / a compiled build.
  let ShapeConfig: Record<string, string>;
  let ShapeParser: typeof import("../src/shapes/parser.js").ShapeParser;
  let SchemaRegistry: typeof import("../src/shapes/schema.js").SchemaRegistry;
  let ShapeParseError: typeof import("../src/errors.js").ShapeParseError;
  let ShapeValidationError: typeof import("../src/errors.js").ShapeValidationError;

  try {
    // Synchronous-style requires aren't available in pure ESM. Use the
    // statically-imported modules — they're hoisted by the bundler / tsx.
    ShapeConfig = (lazyImports.config as Record<string, unknown>).ShapeConfig as Record<
      string,
      string
    >;
    ShapeParser = lazyImports.parser.ShapeParser;
    SchemaRegistry = lazyImports.schema.SchemaRegistry;
    ShapeParseError = lazyImports.errors.ShapeParseError;
    ShapeValidationError = lazyImports.errors.ShapeValidationError;
  } catch (err) {
    warnings.push(
      `shapes: could not load SDK modules for shape validation (${(err as Error).message})`,
    );
    return { errors, warnings };
  }

  const parser = new ShapeParser({ cacheEnabled: true });
  const registry = new SchemaRegistry();

  for (const { shapeName, modelName } of SHAPE_CONFIG_ENTRIES) {
    const shapeString = ShapeConfig[shapeName];
    if (typeof shapeString !== "string" || shapeString.length === 0) {
      warnings.push(`shapes: \`ShapeConfig.${shapeName}\` missing or empty in config.ts`);
      continue;
    }

    // Skip models whose schema isn't registered yet — record as a warning so
    // we can track parity with the Python schema set.
    try {
      registry.getSchema(modelName);
    } catch {
      warnings.push(
        `shapes: \`ShapeConfig.${shapeName}\` references model \`${modelName}\` which has no explicit schema (skipped)`,
      );
      continue;
    }

    try {
      const spec = parser.parse(shapeString);
      validateShapeSpec(spec, modelName, registry);
    } catch (e) {
      if (e instanceof ShapeParseError) {
        errors.push(`shapes: \`ShapeConfig.${shapeName}\` parse error: ${e.message}`);
      } else if (e instanceof ShapeValidationError) {
        errors.push(`shapes: \`ShapeConfig.${shapeName}\` invalid: ${e.message}`);
      } else {
        errors.push(`shapes: \`ShapeConfig.${shapeName}\` unexpected error: ${(e as Error).message}`);
      }
    }
  }

  return { errors, warnings };
}

/**
 * Walk a ShapeSpec and verify every field exists in the schema for its
 * model. Nested fields recurse into the field's nestedModel when present.
 *
 * Wildcards (`*`) are accepted as-is.
 */
function validateShapeSpec(
  spec: { fields: { name: string; nestedFields?: { name: string; nestedFields?: unknown }[] }[] },
  modelName: string,
  registry: import("../src/shapes/schema.js").SchemaRegistry,
): void {
  type Field = {
    name: string;
    nestedFields?: Field[];
  };
  const walk = (fields: Field[], currentModel: string): void => {
    const schema = registry.getSchema(currentModel);
    for (const field of fields) {
      if (field.name === "*") continue;
      const meta = schema.fields[field.name];
      if (!meta) {
        const available = Object.keys(schema.fields).slice(0, 8);
        throw new lazyImports.errors.ShapeValidationError(
          `field "${field.name}" not on model "${currentModel}" (available: ${available.join(", ")}...)`,
        );
      }
      if (field.nestedFields && field.nestedFields.length > 0) {
        if (meta.nestedModel) {
          walk(field.nestedFields as Field[], meta.nestedModel);
        }
        // If there's no nestedModel, we silently accept — mirrors Python
        // behavior, which doesn't recurse into untyped expand fields.
      }
    }
  };
  walk(spec.fields as Field[], modelName);
}

// Statically import SDK modules. Wrapped in a record so `runShapeCheck` can
// access them defensively (and so test code can stub them if needed).
import * as configMod from "../src/config.js";
import * as parserMod from "../src/shapes/parser.js";
import * as schemaMod from "../src/shapes/schema.js";
import * as errorsMod from "../src/errors.js";

const lazyImports = {
  config: configMod,
  parser: parserMod,
  schema: schemaMod,
  errors: errorsMod,
};

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(argv: string[]): { manifest: string } {
  let manifest: string | undefined;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--manifest") {
      manifest = argv[i + 1];
      i += 1;
    } else if (arg.startsWith("--manifest=")) {
      manifest = arg.slice("--manifest=".length);
    } else if (arg === "-h" || arg === "--help") {
      process.stdout.write(
        "Usage: tsx scripts/check-filter-shape-conformance.ts [--manifest PATH]\n",
      );
      process.exit(0);
    }
  }
  return { manifest: manifest ?? DEFAULT_MANIFEST_PATH };
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv.slice(2));
  const manifestPath = path.resolve(args.manifest);

  const result = runConformance({ manifestPath });
  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
  return result.errors.length > 0 ? 1 : 0;
}

// Run main only when invoked directly (not when imported by tests).
const isDirectRun = (() => {
  try {
    const invoked = process.argv[1] ? path.resolve(process.argv[1]) : "";
    return invoked === __filename;
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  main().then((code) => process.exit(code), (err) => {
    process.stderr.write(`conformance script failed: ${(err as Error).stack ?? err}\n`);
    process.exit(2);
  });
}
