import type { FieldSchema, FieldSchemaMap, ExplicitSchemas } from "./schemaTypes.js";

// NOTE: This file is generated from the Tango Python SDK's explicit_schemas.py.
// It provides explicit schema information for all resource types.

export const OFFICE_SCHEMA: FieldSchemaMap = {
  agency: {
    name: "agency",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  code: {
    name: "code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  name: {
    name: "name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const LOCATION_SCHEMA: FieldSchemaMap = {
  city_name: {
    name: "city_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  country_code: {
    name: "country_code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  country_name: {
    name: "country_name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  state_code: {
    name: "state_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  state_name: {
    name: "state_name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  zip_code: {
    name: "zip_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const PLACE_OF_PERFORMANCE_SCHEMA: FieldSchemaMap = {
  city_name: {
    name: "city_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  state_code: {
    name: "state_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  state_name: {
    name: "state_name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  country_code: {
    name: "country_code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  country_name: {
    name: "country_name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  zip_code: {
    name: "zip_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const COMPETITION_SCHEMA: FieldSchemaMap = {
  contract_type: {
    name: "contract_type",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  extent_competed: {
    name: "extent_competed",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  number_of_offers_received: {
    name: "number_of_offers_received",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  other_than_full_and_open_competition: {
    name: "other_than_full_and_open_competition",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  solicitation_date: {
    name: "solicitation_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  solicitation_identifier: {
    name: "solicitation_identifier",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  solicitation_procedures: {
    name: "solicitation_procedures",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const PARENT_AWARD_SCHEMA: FieldSchemaMap = {
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  idv_type: {
    name: "idv_type",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  key: {
    name: "key",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  piid: {
    name: "piid",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const LEGISLATIVE_MANDATES_SCHEMA: FieldSchemaMap = {
  clinger_cohen_act_planning: {
    name: "clinger_cohen_act_planning",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  construction_wage_rate_requirements: {
    name: "construction_wage_rate_requirements",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  employment_eligibility_verification: {
    name: "employment_eligibility_verification",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  interagency_contracting_authority: {
    name: "interagency_contracting_authority",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  labor_standards: {
    name: "labor_standards",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  materials_supplies_articles_equipment: {
    name: "materials_supplies_articles_equipment",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  other_statutory_authority: {
    name: "other_statutory_authority",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  service_contract_inventory: {
    name: "service_contract_inventory",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const SUBAWARDS_SUMMARY_SCHEMA: FieldSchemaMap = {
  count: {
    name: "count",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  total_amount: {
    name: "total_amount",
    type: "Decimal",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const TRANSACTION_SCHEMA: FieldSchemaMap = {
  action_type: {
    name: "action_type",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  modification_number: {
    name: "modification_number",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  obligated: {
    name: "obligated",
    type: "Decimal",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  transaction_date: {
    name: "transaction_date",
    type: "date",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const DEPARTMENT_SCHEMA: FieldSchemaMap = {
  abbreviation: {
    name: "abbreviation",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  code: {
    name: "code",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  name: {
    name: "name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const CONTACT_SCHEMA: FieldSchemaMap = {
  email: {
    name: "email",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  fax: {
    name: "fax",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  full_name: {
    name: "full_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  phone: {
    name: "phone",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  title: {
    name: "title",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const RECIPIENT_PROFILE_SCHEMA: FieldSchemaMap = {
  uei: {
    name: "uei",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  cage_code: {
    name: "cage_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  display_name: {
    name: "display_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  legal_business_name: {
    name: "legal_business_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  parent_uei: {
    name: "parent_uei",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  parent_name: {
    name: "parent_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  business_types: {
    name: "business_types",
    type: "str",
    isOptional: true,
    isList: true,
    nestedModel: null,
  },
  location: {
    name: "location",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: "Location",
  },
};

export const CONTRACT_SCHEMA: FieldSchemaMap = {
  award_date: {
    name: "award_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  awarding_office: {
    name: "awarding_office",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "Office",
  },
  base_and_exercised_options_value: {
    name: "base_and_exercised_options_value",
    type: "Decimal",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  commercial_item_acquisition_procedures: {
    name: "commercial_item_acquisition_procedures",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  competition: {
    name: "competition",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "ContractOrIDVCompetition",
  },
  consolidated_contract: {
    name: "consolidated_contract",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  contingency_humanitarian_or_peacekeeping_operation: {
    name: "contingency_humanitarian_or_peacekeeping_operation",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  contract_bundling: {
    name: "contract_bundling",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  contract_financing: {
    name: "contract_financing",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  cost_accounting_standards_clause: {
    name: "cost_accounting_standards_clause",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  cost_or_pricing_data: {
    name: "cost_or_pricing_data",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  dod_acquisition_program: {
    name: "dod_acquisition_program",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  dod_transaction_number: {
    name: "dod_transaction_number",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  domestic_or_foreign_entity: {
    name: "domestic_or_foreign_entity",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  epa_designated_product: {
    name: "epa_designated_product",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  evaluated_preference: {
    name: "evaluated_preference",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  fair_opportunity_limited_sources: {
    name: "fair_opportunity_limited_sources",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  fed_biz_opps: {
    name: "fed_biz_opps",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  fiscal_year: {
    name: "fiscal_year",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  foreign_funding: {
    name: "foreign_funding",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  funding_office: {
    name: "funding_office",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "Office",
  },
  government_furnished_property: {
    name: "government_furnished_property",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  information_technology_commercial_item_category: {
    name: "information_technology_commercial_item_category",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  inherently_governmental_functions: {
    name: "inherently_governmental_functions",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  key: {
    name: "key",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  legislative_mandates: {
    name: "legislative_mandates",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "LegislativeMandates",
  },
  local_area_set_aside: {
    name: "local_area_set_aside",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  major_program: {
    name: "major_program",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  naics_code: {
    name: "naics_code",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  number_of_actions: {
    name: "number_of_actions",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  number_of_offers_source: {
    name: "number_of_offers_source",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  obligated: {
    name: "obligated",
    type: "Decimal",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  parent_award: {
    name: "parent_award",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "ParentAward",
  },
  performance_based_service_acquisition: {
    name: "performance_based_service_acquisition",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  piid: {
    name: "piid",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  place_of_manufacture: {
    name: "place_of_manufacture",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  place_of_performance: {
    name: "place_of_performance",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "PlaceOfPerformance",
  },
  price_evaluation_percent_difference: {
    name: "price_evaluation_percent_difference",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  psc_code: {
    name: "psc_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  purchase_card_as_payment_method: {
    name: "purchase_card_as_payment_method",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  recipient: {
    name: "recipient",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "RecipientProfile",
  },
  recovered_materials_sustainability: {
    name: "recovered_materials_sustainability",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  research: {
    name: "research",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  sam_exception: {
    name: "sam_exception",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  set_aside: {
    name: "set_aside",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  simplified_procedures_for_certain_commercial_items: {
    name: "simplified_procedures_for_certain_commercial_items",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  small_business_competitiveness_demonstration_program: {
    name: "small_business_competitiveness_demonstration_program",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  solicitation_identifier: {
    name: "solicitation_identifier",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  subawards_summary: {
    name: "subawards_summary",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "SubawardsSummary",
  },
  subcontracting_plan: {
    name: "subcontracting_plan",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  total_contract_value: {
    name: "total_contract_value",
    type: "Decimal",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  tradeoff_process: {
    name: "tradeoff_process",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  transactions: {
    name: "transactions",
    type: "dict",
    isOptional: false,
    isList: true,
    nestedModel: "AwardTransaction",
  },
  type_of_set_aside_source: {
    name: "type_of_set_aside_source",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  undefinitized_action: {
    name: "undefinitized_action",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const ENTITY_SCHEMA: FieldSchemaMap = {
  business_types: {
    name: "business_types",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  cage_code: {
    name: "cage_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  capabilities: {
    name: "capabilities",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  congressional_district: {
    name: "congressional_district",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  country_of_incorporation_code: {
    name: "country_of_incorporation_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  country_of_incorporation_desc: {
    name: "country_of_incorporation_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  dba_name: {
    name: "dba_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  dodaac: {
    name: "dodaac",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  email_address: {
    name: "email_address",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_division_name: {
    name: "entity_division_name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_division_number: {
    name: "entity_division_number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_start_date: {
    name: "entity_start_date",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_structure_code: {
    name: "entity_structure_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_structure_desc: {
    name: "entity_structure_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_type_code: {
    name: "entity_type_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_type_desc: {
    name: "entity_type_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  entity_url: {
    name: "entity_url",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  evs_source: {
    name: "evs_source",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  exclusion_status_flag: {
    name: "exclusion_status_flag",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  exclusion_url: {
    name: "exclusion_url",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  federal_obligations: {
    name: "federal_obligations",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  fiscal_year_end_close_date: {
    name: "fiscal_year_end_close_date",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  highest_owner: {
    name: "highest_owner",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  immediate_owner: {
    name: "immediate_owner",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  keywords: {
    name: "keywords",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  last_update_date: {
    name: "last_update_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  legal_business_name: {
    name: "legal_business_name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  mailing_address: {
    name: "mailing_address",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  naics_codes: {
    name: "naics_codes",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  organization_structure_code: {
    name: "organization_structure_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  organization_structure_desc: {
    name: "organization_structure_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  physical_address: {
    name: "physical_address",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  primary_naics: {
    name: "primary_naics",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  profit_structure_code: {
    name: "profit_structure_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  profit_structure_desc: {
    name: "profit_structure_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  psc_codes: {
    name: "psc_codes",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  public_display_flag: {
    name: "public_display_flag",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  purpose_of_registration_code: {
    name: "purpose_of_registration_code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  purpose_of_registration_desc: {
    name: "purpose_of_registration_desc",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  registered: {
    name: "registered",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  registration_status: {
    name: "registration_status",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  relationships: {
    name: "relationships",
    type: "str",
    isOptional: false,
    isList: true,
    nestedModel: null,
  },
  sam_activation_date: {
    name: "sam_activation_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  sam_expiration_date: {
    name: "sam_expiration_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  sam_registration_date: {
    name: "sam_registration_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  sba_business_types: {
    name: "sba_business_types",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  state_of_incorporation_code: {
    name: "state_of_incorporation_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  state_of_incorporation_desc: {
    name: "state_of_incorporation_desc",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  submission_date: {
    name: "submission_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  uei: {
    name: "uei",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  uei_creation_date: {
    name: "uei_creation_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  uei_expiration_date: {
    name: "uei_expiration_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  uei_status: {
    name: "uei_status",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const FORECAST_SCHEMA: FieldSchemaMap = {
  agency: {
    name: "agency",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  anticipated_award_date: {
    name: "anticipated_award_date",
    type: "date",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  contract_vehicle: {
    name: "contract_vehicle",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  estimated_period: {
    name: "estimated_period",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  external_id: {
    name: "external_id",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  fiscal_year: {
    name: "fiscal_year",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  id: {
    name: "id",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  is_active: {
    name: "is_active",
    type: "bool",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  naics_code: {
    name: "naics_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  place_of_performance: {
    name: "place_of_performance",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  primary_contact: {
    name: "primary_contact",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  set_aside: {
    name: "set_aside",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  source_system: {
    name: "source_system",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  status: {
    name: "status",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  title: {
    name: "title",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const OPPORTUNITY_SCHEMA: FieldSchemaMap = {
  active: {
    name: "active",
    type: "bool",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  attachments: {
    name: "attachments",
    type: "dict",
    isOptional: false,
    isList: true,
    nestedModel: "OpportunityAttachment",
  },
  award_number: {
    name: "award_number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  first_notice_date: {
    name: "first_notice_date",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  last_notice_date: {
    name: "last_notice_date",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  meta: {
    name: "meta",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  naics_code: {
    name: "naics_code",
    type: "int",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  notice_history: {
    name: "notice_history",
    type: "dict",
    isOptional: false,
    isList: true,
    nestedModel: "NoticeHistory",
  },
  office: {
    name: "office",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: "Office",
  },
  opportunity_id: {
    name: "opportunity_id",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  place_of_performance: {
    name: "place_of_performance",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  primary_contact: {
    name: "primary_contact",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: "Contact",
  },
  psc_code: {
    name: "psc_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  response_deadline: {
    name: "response_deadline",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  sam_url: {
    name: "sam_url",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  set_aside: {
    name: "set_aside",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  solicitation_number: {
    name: "solicitation_number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  title: {
    name: "title",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const NOTICE_SCHEMA: FieldSchemaMap = {
  active: {
    name: "active",
    type: "bool",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  attachment_count: {
    name: "attachment_count",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  award_number: {
    name: "award_number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  last_updated: {
    name: "last_updated",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  naics_code: {
    name: "naics_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  notice_id: {
    name: "notice_id",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  opportunity: {
    name: "opportunity",
    type: "dict",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  posted_date: {
    name: "posted_date",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  psc_code: {
    name: "psc_code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  response_deadline: {
    name: "response_deadline",
    type: "datetime",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  sam_url: {
    name: "sam_url",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  set_aside: {
    name: "set_aside",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  solicitation_number: {
    name: "solicitation_number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  title: {
    name: "title",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const AGENCY_SCHEMA: FieldSchemaMap = {
  abbreviation: {
    name: "abbreviation",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  code: {
    name: "code",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  department: {
    name: "department",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  name: {
    name: "name",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
};

export const CFDA_NUMBER_SCHEMA: FieldSchemaMap = {
  number: {
    name: "number",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  title: {
    name: "title",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const CODE_DESCRIPTION_SCHEMA: FieldSchemaMap = {
  code: {
    name: "code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const GRANT_ATTACHMENT_SCHEMA: FieldSchemaMap = {
  attachment_id: {
    name: "attachment_id",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  mime_type: {
    name: "mime_type",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  name: {
    name: "name",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  posted_date: {
    name: "posted_date",
    type: "datetime",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  resource_id: {
    name: "resource_id",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  type: {
    name: "type",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  url: {
    name: "url",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
};

export const GRANT_SCHEMA: FieldSchemaMap = {
  agency_code: {
    name: "agency_code",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  applicant_eligibility_description: {
    name: "applicant_eligibility_description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  description: {
    name: "description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  funding_activity_category_description: {
    name: "funding_activity_category_description",
    type: "str",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  grant_id: {
    name: "grant_id",
    type: "int",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  grantor_contact: {
    name: "grantor_contact",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: null,
  },
  last_updated: {
    name: "last_updated",
    type: "datetime",
    isOptional: true,
    isList: false,
    nestedModel: null,
  },
  opportunity_number: {
    name: "opportunity_number",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  status: {
    name: "status",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: "CodeDescription",
  },
  title: {
    name: "title",
    type: "str",
    isOptional: false,
    isList: false,
    nestedModel: null,
  },
  cfda_numbers: {
    name: "cfda_numbers",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: "CFDANumber",
  },
  applicant_types: {
    name: "applicant_types",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: "CodeDescription",
  },
  category: {
    name: "category",
    type: "dict",
    isOptional: true,
    isList: false,
    nestedModel: "CodeDescription",
  },
  funding_categories: {
    name: "funding_categories",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: "CodeDescription",
  },
  funding_details: {
    name: "funding_details",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: null,
  },
  funding_instruments: {
    name: "funding_instruments",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: "CodeDescription",
  },
  important_dates: {
    name: "important_dates",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: null,
  },
  attachments: {
    name: "attachments",
    type: "dict",
    isOptional: true,
    isList: true,
    nestedModel: "GrantAttachment",
  },
};

export const EXPLICIT_SCHEMAS: ExplicitSchemas = {
  Office: OFFICE_SCHEMA,
  Location: LOCATION_SCHEMA,
  PlaceOfPerformance: PLACE_OF_PERFORMANCE_SCHEMA,
  Competition: COMPETITION_SCHEMA,
  ParentAward: PARENT_AWARD_SCHEMA,
  LegislativeMandates: LEGISLATIVE_MANDATES_SCHEMA,
  SubawardsSummary: SUBAWARDS_SUMMARY_SCHEMA,
  Transaction: TRANSACTION_SCHEMA,
  Department: DEPARTMENT_SCHEMA,
  Contact: CONTACT_SCHEMA,
  RecipientProfile: RECIPIENT_PROFILE_SCHEMA,
  Contract: CONTRACT_SCHEMA,
  Entity: ENTITY_SCHEMA,
  Forecast: FORECAST_SCHEMA,
  Opportunity: OPPORTUNITY_SCHEMA,
  Notice: NOTICE_SCHEMA,
  Agency: AGENCY_SCHEMA,
  Grant: GRANT_SCHEMA,
  CFDANumber: CFDA_NUMBER_SCHEMA,
  CodeDescription: CODE_DESCRIPTION_SCHEMA,
  GrantAttachment: GRANT_ATTACHMENT_SCHEMA,
};
